### ISSUE TITLE
Update entry for "backward compatible"

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#157]
From email thread:

Corporate Style Guide:
backward
Avoid using "backwards" unless you are stating that something has "backwards compatibility."

RH Style Guide (agrees with IBM)
backwards compatible
    Do not use. Instead, use "compatible with earlier versions."

https://www.merriam-webster.com/dictionary/backward%20compatible
Definition of backward compatible
: compatible with older equipment or previous versions of software

Personally, given the widespread use and understanding of the term, especially in IT, I'm not opposed to using the M-W definition. The IBM definition is quite old, and seems unnecessarily long.

**Comment by sffrench** [comment]
@daobrien I have made the changes ([PR here](https://github.com/StyleGuides/WritingStyleGuide/pull/205)), however, I can't quite figure out exactly what you wanted me to change. I have added "backwards" and changed backwards compatible to be used to refer to something that is compatible with older equipment or previous versions of software. 

In the guide "backwards compatible" links to "forward compatible", wasn't sure what to do here, because forward compatible is not as widely known and doesn't even have a definition in the Merriam Webster dictionary. I have left the link, not sure if it makes sense to leave the link now though. Unless I am completely off the mark and you did not want me to change backwards compatible?
