### ISSUE TITLE
Standardize terms to describe command line arguments, options and parameters

### ISSUE THREAD

**Issue by alexpdp7** [StyleGuides/WritingStyleGuide#199]
The IBM Style Guide is not very clear about how the use of options/arguments and parameters (see Command and Command Syntax sections). It seems that in `ls --foo bar`, `foo` would be a parameter, and `bar` would be the option.

https://stylepedia.net/style/#documenting-command-syntax talks about options, but doesn't go into much detail.

It seems that neither describes the most common conventions such as:

* "--option argument"  and "command --option argument argument"
* "command --option parameter argument"

so it might be worth overriding the IBM style guide to reflect common usage.

See some further discussion in https://chat.google.com/room/AAAAzASo1xY/IZ1H3MyZJ-k

**Comment by bonnevil** [comment]
As `info bash` says: "A simple shell command such as 'echo a b c' consists of the command itself followed by arguments, separated by spaces."  

Then if you read `info libc`, which is authoritative for this, it continues with statements like: "POSIX recommends these conventions for command line arguments. [...] Arguments are options if they begin with a hyphen delimiter (‘-’). Multiple options may follow a hyphen delimiter in a single token if the options do not take arguments.  Thus, ‘-abc’ is equivalent to ‘-a -b -c’.  [...]  Certain options require an argument.  For example, the ‘-o’ command of the ‘ld’ command requires an argument—an output file name."  and so on.  See `info libc "argument syntax"` for the full discussion.

"Parameter" gets confusing because in Bash, we talk about "parameter and variable expansion": `$1` and `$$` are both "parameters" (a positional parameter and a special parameter respectively) that are handled like variables.

You can actually see that Bash considers options to be a special kind of argument, by using positional parameters.  Write a shell script:
```
#!/bin/bash
echo $1
echo $2
```
Set it executable, and run `script -o argument`.  `$1` (the first argument) will be `-o` and `$2` (the second argument) will be `argument`.  But we almost always refer to options as options for clarity, unless we're doing something to parse a command line like this.

**Comment by bonnevil** [comment]
I think when we're talking about things like the command line as specified by Bash and POSIX, we need to follow the terminology the software uses.  We never use "flag" when talking about command line options in POSIX, even though Microsoft often uses the term "flag" when referring to single-character options in Microsoft Windows.  If the style guide said to follow the Microsoft standard here, we'd be wrong and we'd be teaching the wrong terminology to students.

**Comment by daobrien** [comment]
Sticking this here as an example, just something to work with. Use or ignore as desired. This is from OpenStack.

```
Use the <code>manila-type create</code> command to create the share type.
The <code>false</code> argument represents the value of the <code>driver_handles_share_servers</code> parameter.
```

**Comment by daobrien** [comment]
> I think when we're talking about things like the command line as specified by Bash and POSIX, we need to follow the terminology the software uses. We never use "flag" when talking about command line options in POSIX, even though Microsoft often uses the term "flag" when referring to single-character options in Microsoft Windows. If the style guide said to follow the Microsoft standard here, we'd be wrong and we'd be teaching the wrong terminology to students.

I like this, and would like to fall back on it as our convention. I'll write something up based on this, and taking the other comments into account, and make it available for review.
