### ISSUE TITLE
Change book subtitle from "Conventions for Writers and Editors" to "Red Hat Style Guide".

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#251]

**Comment by daobrien** [comment]
My issue with this is that this is more focused than "Red Hat Style Guide" might suggest. It's a style guide for technical writing. Neither is it used by all of RH. Brand and Marketing, etc., have their own guide, as does GSS, I think, which they use for writing KBase articles.

I understand where the desire to change this is coming from; when you open the guide in a browser the subtitle is what appears on the tab, and is truncated.

@nmuller66 @sffrench ?

**Comment by bonnevil** [comment]
Isn't there already a "Red Hat Style Guide" corporate-wide?  The renaming would be confusing, if so.

**Comment by julian-cable** [comment]
To eliminate any ambiguity, how about something like "Red Hat Writing Style Guide for Technical Content"?

**Comment by daobrien** [comment]
The corporate guide is called just that, although it contains pointers to this guide and another as well. It is currently (or last I heard) being transitioned to a public guide.
https://source.redhat.com/groups/public/word-nerds/red_hat_word_nerds_wiki/corporate_style_guide

I also don't know why but I'd always had it in my mind that the actual title contained "Technical Writing" (because that's what it's for). But, I don't often look at the title and this escaped me. The subtitle of "Conventions for Writers and Editors" separates this guide from any UI design docs, but there is still no obvious focus on the "technical" aspect.

**Comment by sffrench** [comment]
I am of the opinion, if it isn't broke, then don't fix it. But can also agree that some further clarity wouldn't go a miss.

**Comment by daobrien** [comment]
The current proposal produces the following, which a) helps to address the issue the name on the browser tab, b) provides more focus on what the guide is actually about, and c) doesn't differ very much from what we already have.

![Screenshot from 2021-07-29 20-25-49](https://user-images.githubusercontent.com/1518237/127481926-3888e92b-e25c-41c2-abe7-68089332ba9d.png)

![Screenshot from 2021-07-29 20-22-33](https://user-images.githubusercontent.com/1518237/127481957-f816bb10-5508-4fcd-907d-fb58adc5066a.png)
