### ISSUE TITLE
Merge dev to master

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#433]

**Comment by nmuller66** [comment]
@daobrien Hey David, Julian created this issue to do the final merge of the changes from resolved issues into the master branch so we can publish.  I think this requires building a PR in `dev` that contains all the changes since the last merge to `master` and then selecting the source and destination branches from the drop-down lists at the top of the PR, but could you confirm or provide additional clarity about the steps? 

J
![image](https://user-images.githubusercontent.com/50212653/204925440-aff0add6-fd73-42d8-a878-06ce9d672063.png)
