### ISSUE TITLE
Update how to refer to special characters

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#541]
Rename heading 2.9.8 to "Referring to Punctuation Marks and Special Characters". 

Add examples for referring to a symbol in parentheses. 
Explain that the symbol name comes after any noun that describes the symbol. 

Examples (incorrect):
- Use the plus (+) symbol.
- Add the pipe (|) character.
- The hyphen after the greater-than (>) sign indicates that a newline (\n) character is not added to the end of the variable.

Examples (correct):
- Use the plus symbol (+).
- Add the pipe character (|).
- The hyphen after the greater-than sign  (>) indicates that a newline character (\n) is not added to the end of the variable.

**Comment by daobrien** [comment]
> Rename heading 2.9.8 to "Referring to Punctuation Marks and Special Characters".

You might want to look at 2.9.8 and 2.9.9 and make sure they flow.
> 
> Add examples for referring to a symbol in parentheses. Explain that the symbol name comes after any noun that describes the symbol.
> 
> Examples (incorrect):
> 
> * Use the plus (+) symbol.
> * Add the pipe (|) character.
> * The hyphen after the greater-than (>) sign indicates that a newline (\n) character is not added to the end of the variable.
> 
> Examples (correct):
> 
> * Use the plus symbol (+).
> * Add the pipe character (|).
> * The hyphen after the greater-than sign  (>) indicates that a newline character (\n) is not added to the end of the variable.

I wouldn't use the first two as examples of correct usage; not because they're wrong but because there are better examples. E.g., "Click the plus character (+) to add a new node." and "Use the pipe character (|) to send the output of one program to the input of another."

We should also consider using a single term as much as possible, such as character or symbol, to refer to these. I think we currently use about four different terms: character, symbol, sign, and mark. Not sure about any others.

@sffrench @rclee33

**Comment by rclee33** [comment]
In terms of the examples: I suggest keeping one of the shorter examples to show that it's acceptable to end a sentence with the sign itself (enclosed in backticks and in parenthesis). 

In terms of using a single term such as character, symbol, sign, etc.: I generally go by the "punctation names" table in the guide. Some names do include the word sign, symbol, etc., and some do not. If we're seeking consistency, we'd need to start there. 

But: Although I understand the desire to have one term for consistency, in this case, there are conventions for some of these punctuation names that account for the variety, and I'm not sure that implementing one word to rule them all (ex: "symbol") would be effective. For example, it would be unexpected to encounter "equal symbol" instead of "equal sign". In this case, I think we should abide by the general naming conventions, even if that results in using a few different terms for some of the punctuation names.
