### ISSUE TITLE
Clarify 'apostrophe' vs 'single quotation mark'

### ISSUE THREAD

**Issue by someth2say** [StyleGuides/WritingStyleGuide#555]
The punctuation section states (formatted for clarity):
```html
<row><entry> &apos; </entry><entry> Apostrophe </entry><row>
...
<row><entry> &apos; </entry><entry> Single quotation mark </entry></row>
```
As you can see, the same symbol is used in both cases.
This leads to confusion.

Maybe we can indicate both punctuation elements are written as the same symbol, clarifying the use cases?

**Comment by julian-cable** [comment]
From Google Chat, 30 January 2024:

Julian:
Hi Jordi, I was looking at this issue that you raised for the style guide:
https://github.com/StyleGuides/WritingStyleGuide/issues/555

Quotation marks sometimes use the same symbol as an apostrophe, but not always:
https://stylepedia.net/style/6.1/#quotation-marks

I am not sure if the table of symbols, in section 2.9.9, is the right place to discuss use cases.
What do you think?

Jordi Sola Alaball, Yesterday 11:52
Yes, I agree.
This topic is hairy: it covers typography, translations and what-not.
Maybe worth having a separated section to discuss it, yes

Julian, Yesterday 11:54
Section 2.9.5 already discusses it. 
I suppose one option might be to add a cross-reference from the table to that section, although it might add clutter to the table

Jordi Sola Alaball, Yesterday 12:02
I feel that 2.9.5 is more or less ok.
Maybe 2.9.6 can talk about other usages of apostrophes. Right now, it talks about posessives (saxon genitive) and plurals. I wonder if we also slightly comment about apostrophes in other languages.

In fact, this proposal came from https://github.com/RedHatTraining/scaffolding/pull/983/files
In this PR the translation team replaces straight apostrophes (a.k.a single quotes) with typographic apostrophes.
I am convinced that, in this case, we should use typographic apostrophes, but the guidance in the stylepedia seems to propose otherwise.

Julian, Yesterday 12:06
This latter use case is new to me: may I ask why typographic apostrophes are being adopted instead for French (or is it for all other languages than English)?

Jordi Sola Alaball, Yesterday 13:12
I am not 100, but I think that is the standard in French.
Lène can provide more details, or she can lead us to people much more savvy than me.

Julian, Yesterday 13:59
OK, I will ask Lène, and then will plan to update or add accordingly in the style guide. Thanks

You, Yesterday 17:34
I had a call with Lène to discuss apostrophes for translation. 
She said that the changes in https://github.com/RedHatTraining/scaffolding/pull/983/files, which use curly apostrophes, relate to phrases in the translation memory for French.
(Other French translated content might instead use straight apostrophes, which is not ideal, so she will separately check this point, to ensure consistency.)
She thinks (and I agree) that our style guide should cover only original content in English. Lène's team has a separate set of style guides, one for each language. 

Coming back to our style guide, maybe a change to make for now is to update the symbols table to show that apostrophes, single and double quotation marks can each be either the straight or the curly version. Would that approach be valid, and sufficient, in your opinion?

Jordi Sola Alaball, Yesterday 17:52
Yes, that sounds like a safe plan. 
As long as we state the different versions of each symbol, I think we'll be good.

You, Yesterday 17:55
OK, let me work on an update and I'll share a draft for you to look at.
