### ISSUE TITLE
Remove or rework "dialog box" entry

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#567]
The current word usage entry for "dialog box" should be removed because it refers to an entry for that term in IBM Style that no longer exists (IBM removed that entry).

Consider whether to provide any additional guidance on what term to use instead to refer to such a UI element (such as dialog, dialog box, window, or other).

**Comment by daobrien** [comment]
I wouldn't remove the actual entry; just remove the reference to IBM and include our own guidance, that "dialog box" is correct and "dialog" or "dialogue" or "window" or whatever are not. Include a couple of examples and mention that it applies to both modal and non-modal types. People might be inclined to refer to non-modal types as windows; I don't' know.

This probably needs to happen sooner rather than later so that ppl aren't referring to IBM and then getting told not to.
