### ISSUE TITLE
Add guidance for "sign-in"

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#576]
The style guide has guidance for "sign in" as a verb; also add guidance to use "sign-in" as a noun or adjective. This is needed for documenting using the UI in AWS ROSA.

**Comment by daobrien** [comment]
If you mean that particular UI uses "sign-in" as an object name or similar then
no updates are required.

This is standard practice; when documenting UIs use the word form as it appears
in the UI. In basically all other cases (other exceptions probably exist), use
the guidance from the style guide.

This is why we sometimes see (e.g.), "life cycle" or "life-cycle" or whatever
instead of the documented usage of "lifecycle". The UI designers do not consult
our style guide when designing UIs and that's why we end up with these
differences.

If you add "sign-in" as an alternative form then it opens the door for people to
use it where they shouldn't. If there is a valid use case for either of these
forms outside of a UI then we can consider adding it.

**Comment by julian-cable** [comment]
The use case that I encountered in a course was as follows:
In an exercise, students work with AWS. 
The Amazon UI uses "Sign in" (not "Log in"). 
One exercise step included an occurrence of "sign in" as a verb, and another as an adjective: 
"Sign in by using your IAM user account ID."
"If the sign in page offers two options ..."

I corrected the latter occurrence to "sign-in". I noticed that the style guide contains an entry for "sign in" (verb), but no mention of what to do for other parts of speech. For clarity and completeness, I want to add an entry for "sign-in" (adjective, noun). The use case would be different from "login", hence the need for explicit guidance. The intent is not to prefer "sign-in" over "login", or vice versa.

**Comment by rclee33** [comment]
I think Julian's suggested clarification makes sense. Hyphenating compound modifiers is often a challenge, so I think extra guidance on this issue would be useful for devs. With this update, the two entries (for "log in" and "sign in") would then be consistent with each other (by including usage for different parts of speech). Sounds good to me!

**Comment by daobrien** [comment]
> "Sign in by using your IAM user account ID."
That's fine. If the UI uses "sign in" we can use that too.

> "If the sign in page offers two options ..."
You need to check what the actual name of the page is (or whatever it is; "page" is a bit vague). You might be able to change it to "authentication"; e.g., if two authentication options are available... or whatever. If "the signin page" really does seem to be correct, stick with the one-word form.

afaict the hyphenated form doesn't appear anywhere. The one-word form as a noun is fine; that appears in multiple dictionaries. I'm happy to just add the one-word form as a noun and adjective as an adjunct to the existing verb entry.

**Comment by julian-cable** [comment]
IBM uses "sign-on" and "sign-off" (n, adj). I propose that we do likewise for "sign-in". I must admit that "signin" looks rather odd and confusing, maybe because of the repeated "i" and "n". 

@rclee33 @sffrench, what do you think? 

Also, the corporate style guide has "sign-up" (n, adj).

**Comment by rclee33** [comment]
I don't recall seeing "signin" in the wild, and I agree that it looks confusing. I think it's because it's easy to misread as a typo for "signing". In this case ("sign-in page"), I interpreted "sign-in" as a compound modifier for the noun "page". 

Our dictionary of record (Merriam-Webster) only lists the transitive verb form of "sign in", so that's not much help. But, all of that said, I don't see a reason to deviate from IBM here.

**Comment by daobrien** [comment]
How about ask in WN and see if we can get some sort of consensus.

There are plenty of knowledgeable ppl out there to lean on.

I'm ok with whatever the majority decides.

Julian,
what would be helpful is a screenshot of the UI where this appears. Visuals
often help people to think.
thanks

**Comment by julian-cable** [comment]
Here is a screenshot to show the context. 
I'll also ask Word Nerds what they think. 
![Screenshot from 2024-06-17 11-45-33](https://github.com/StyleGuides/WritingStyleGuide/assets/79939933/718a850e-4808-4e09-ac39-a2861af5a690)

**Comment by julian-cable** [comment]
Word Nerds has confirmed that "sign-in" is correct, and aligns with my own thinking. Will add to the guide.
