### ISSUE TITLE
Add ePub to WUG

### ISSUE THREAD

**Issue by rclee33** [StyleGuides/WritingStyleGuide#599]
I suggest adding "ePub" to the WUG.

**Comment by daobrien** [comment]
More info? Do you mean "write ePub and not epub or EPUB or whatever"? Do you want to include a definition of what it actually means? I've never thought about it before but why ePub and not Epub or anything else? Is this a style guide issue or just a spelling issue? What do other grouups use? Thanks

**Comment by rclee33** [comment]
Sorry for not including much detail! Yes, I meant to describe which styling we prefer ("write ePub and not epub or EPUB or whatever"). I do think it's a styling issue, since there are several ways to style it (ePub, EPUB, e-pub, etc.). Part of this discussion (I think) is whether to treat "ePub" as a file type ("EPUB"), or whether it's acceptable to use "ePub" as a noun to refer to the file itself ("the ePub"; "the ePub viewer", etc.).

We discussed using "ePub" when updating the `sk` template for CH00 content to include a description of optimal sizing for ePub viewers ([comment thread on PR](https://github.com/RedHatTraining/scaffolding/pull/1070#discussion_r1629799787)). At that time, we landed on "ePub". 

IBM Style WUG has an [entry for "ebook"](https://www.ibm.com/docs/en/ibm-style?topic=word-usage#ebook) (use as shown) and [an entry for "EPUB"](https://www.ibm.com/docs/en/ibm-style?topic=word-usage#epub) ("Do not use EPUB as a noun to refer to an EPUB file."). 

The RH Training Bookshelf UI uses two different stylings ("e-book" and "eBook"), which I have reported in a Jira to that team.

Perhaps another part of this conversation is whether to use "eBook" or "ePub" (or both?) to refer to our deliverables.

**Comment by julian-cable** [comment]
Interesting points to consider. 

I would tend to prefer "ePub" over "EPUB", because all-caps can come across as "shouty". I would agree with the part of IBM's advice not to use the term as a noun (but as an adjective). 

We also have an entry for various terms that include "e-book". I would prefer not to refer to the hyphenated form any more. Given that the UI has not settled on a single standard, maybe it is too soon for us to specify one over the other?

**Comment by daobrien** [comment]
The fact that the UI has not settled on a standard I think is the perfect time for us to speak up and say "Use this, not that".

The CSG says to refer to AP or IBM, whichever is your fallback, which leaves us with "ebook" and not "epub" (in any form). They treat EPUB the same way they treat PDF; as a file type.

@rclee33 Do you have a link to the Jira? I think it would be a good idea if we shared these types of issues (i.e., CC all the editors) in the future so that we can all keep track, contribute, etc. I also wonder about this:

~~~
We discussed using "ePub" when updating the sk template for CH00 content to include a description of optimal sizing for ePub viewers (comment thread on PR). At that time, we landed on "ePub".
~~~

I obviously missed that discussion on GH, or I would have said that ^^. This sounds... trivial, perhaps, deciding whether to write epub or ePub or whatever, but:
- one group makes a decision on epub
- this decision gets taken by a couple of participants back to their groups
- that decision gets propagated, especially so now that "epub" is our preferred format
- we later learn that we should not be writing epub at all (maybe), and all the changes made, all the docs created, styles updated, etc., have to get changed
- then we have to re-educate ppl.

Am I rambling yet? :) This is one area - terminology and consistency - that I tend to get picky about, so bear with me.

All that said, I vote for "ebook", or IOW, do what IBM says in this case.

**Comment by daobrien** [comment]
@sffrench I'd appreciate your input when you get back. Thanks.

**Comment by rclee33** [comment]
Re: the issue I raised with the Bookshelf team: sorry I didn't share that info more widely before. 

The original ServiceNow ticket is here: https://redhat.service-now.com/help?id=rh_ticket&table=sc_req_item&sys_id=addefaeb47b5ca5066394ab3636d4308 

The RHT Bookshelf team then opened this ticket: https://issues.redhat.com/browse/ITTCAPPS-6951

**Comment by julian-cable** [comment]
If it's appropriate for us to make a decision at this point, then I would go for "ePub" and "ebook".

**Comment by daobrien** [comment]
> If it's appropriate for us to make a decision at this point, then I would go for "ePub" and "ebook".

Well, two things...
1. I think "us" should be RHT as a whole (not just we four, although we should probably be the primary influencers).
2. Why both ePub and ebook? Any particular reason for not following IBM?

**Comment by julian-cable** [comment]
I'm less keen on "EPUB", which IBM uses, because as previously mentioned, I find it shouty.

**Comment by daobrien** [comment]
> I'm less keen on "EPUB", which IBM uses, because as previously mentioned, I find it shouty.

Ah, I thought you meant if we used it to refer to the publication itself. What about PDF, and HTML, etc? I don't really see it as an issue if you're referring to "an EPUB file", etc.

CMOS also uses it:
"Ebook formats include EPUB, a standard that features reflowable text (though fixed layouts are also supported), and PDF, a standard for fixed-layout books."

I understand the relationship between all caps and the appearance of "shouting" in some cases (Do NOT use ALL CAPS to make something seem important) but in this case we're just referring to file types. The same applies to protocols, variables, and some file names, such as `README`, which is all but a standard in many domains.

**Comment by daobrien** [comment]
"EPUB" is also part of the w3.org publishing standards: https://www.w3.org/publishing/epub3/

**Comment by sffrench** [comment]
I would need more opinions to really understand what is needed here. But from the information that has been shared, my personal preference is the same as the IBM guide, because that is the guidance that already exists and I don't feel strongly about it being inaccurate. However I do think that naturally an inclination to capitalize at the least the e and the p will occur, making ePub or ebook possibly a regular error. 
I do think that most people are familiar with "ePub" and "ebook" so that might probably be the more natural thing to write also.

**Comment by daobrien** [comment]
> I would need more opinions to really understand what is needed here. But from the information that has been shared, my personal preference is the same as the IBM guide, because that is the guidance that already exists and I don't feel strongly about it being inaccurate. However I do think that naturally an inclination to capitalize at the least the e and the p will occur, making ePub or ebook possibly a regular error. I do think that most people are familiar with "ePub" and "ebook" so that might probably be the more natural thing to write also.

I think the two main things to consider are 1. how we refer to our deliverables in this format, and 2. how we refer to the format of those deliverables.

If we start with how we refer to PDF files, we don't call them "PDFs" (at least, we're not supposed to). "PDF" in all caps is the name of the standard developed by Adobe. Obviously enough you see `.pdf` as a file extension every day, but that's not referring to the standard. The deliverables themselves we refer to as PDF files or PDF documents or whatever.

Similarly for HTML files, where you see `.html` and even `.htm` as file extensions.

The EPUB format is what we use to produce our deliverables, and it's that format that is defined by the W3C. How we refer to the actual deliverables is probably up to us. I'm disinclined, however, to say "Use EPUB for this and ePub for that" or similar, because a) it contradicts what's in IBM, and b) it's harder to write automated tests. It's easy to write a test for "ebook".

I agree, ppl will be familiar with ePub and ebook and maybe eBook or e-Pub, but that's possibly because so far we haven't had any guidance in place for correct usage. afaict, IBM provides what we need, it agrees with W3C, and I'm happy to use it.

hth

**Comment by julian-cable** [comment]
I think that one difference here is that PDF and HTML are initialisms, whereas EPUB is not (but rather is more like ebook or email in this way). 

Nevertheless, having now reviewed what is in https://www.w3.org/publishing/epub3/, it is clear that "EPUB" is an official designation and, on that site, is even marked with the registered trademark symbol at its first occurrence, as EPUB®. I now think that this overrides all other considerations, and am changing my view to be that we should be using "EPUB" and no other spelling for that term. I propose adding an entry to the WUG to this effect. 

Also, I propose updating the existing entry from using "e-book" to using "ebook" now.

**Comment by sffrench** [comment]
Thank you, @julian-cable, for researching this a little deeper; I am in total agreement with your proposals

**Comment by daobrien** [comment]
> Thank you, @julian-cable, for researching this a little deeper; I am in total agreement with your proposals

You're welcome ;-)

**Comment by sffrench** [comment]
Your research, too, @daobrien @rclee33
